"use client"
import './globals.css';
import Header from '@/components/Header';
import { ThemeProvider } from 'next-themes';
import Navbar from '@/components/Navbar';
import SearchBox from '@/components/SearchBox.jsx';

export const metadata = {
  title: 'IMDb',
  description: 'Generated by create next app',
}

const RootLayout = ({ children })=> {
  return ( <>
      <html lang="pt-BR">
        <body>
            <ThemeProvider enableSystem={true} attribute='class'>
              <div className='dark:bg-gray-700 dark:text-gray-200 text-gray-700 transition-colors duration-300 min-h-screen select-none'>
                <Header />
                <Navbar />
                <div className='container sm:mx-auto max-w-6xl px-3 sm:px-2'>
                  <SearchBox />
                {children} 
                </div>
              </div>
            </ThemeProvider>
        </body>
      </html>
    </>
  )
}

export default RootLayout;
